<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZatcaIntegratorV2\ZatcaIntegratorV2.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BouncyCastle.Crypto">
      <HintPath>bin\Debug\net8.0\BouncyCastle.Crypto.dll</HintPath>
    </Reference>
    <Reference Include="saxon">
      <HintPath>bin\Debug\net8.0\saxon.dll</HintPath>
    </Reference>
    <Reference Include="System.Security.Cryptography.Pkcs">
      <HintPath>bin\Debug\net8.0\System.Security.Cryptography.Pkcs.dll</HintPath>
    </Reference>
    <Reference Include="System.Security.Cryptography.Xml">
      <HintPath>bin\Debug\net8.0\System.Security.Cryptography.Xml.dll</HintPath>
    </Reference>
    <Reference Include="xerces">
      <HintPath>bin\Debug\net8.0\xerces.dll</HintPath>
    </Reference>
    <Reference Include="ZATCA.EInvoice.SDK">
      <HintPath>bin\Debug\net8.0\ZATCA.EInvoice.SDK.dll</HintPath>
    </Reference>
    <Reference Include="ZATCA.EInvoice.SDK.Contracts">
      <HintPath>bin\Debug\net8.0\ZATCA.EInvoice.SDK.Contracts.dll</HintPath>
    </Reference>
    <Reference Include="ZATCA.EInvoice.SDK.Saxon">
      <HintPath>bin\Debug\net8.0\ZATCA.EInvoice.SDK.Saxon.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
